[versions]
asm = "9.6"
kotlin = "1.7.20"
android = "7.4.0"
testing-utils = "2.0.0"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }

[bundles]
asm = ["asm", "asm-util"]

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
artifactPublisher = { id = "com.likethesalad.artifact-publisher", version = "2.0.1" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "3.1.0" }