name: Publish to Gradle Plugin Portal
description: Publishes the Gradle plugin to the Gradle Plugin Portal.
inputs:
  gradle-publish-key:
    description: Gradle Plugin Portal API key
    required: true
  gradle-publish-secret:
    description: Gradle Plugin Portal API secret
    required: true
  gpg-private-key:
    description: Armored GPG private key for artifact signing
    required: true
  gpg-password:
    description: GPG key passphrase
    required: true
runs:
  using: composite
  steps:
    - name: Publish to Gradle Plugin Portal
      shell: bash
      env:
        GRADLE_PUBLISH_KEY: ${{ inputs.gradle-publish-key }}
        GRADLE_PUBLISH_SECRET: ${{ inputs.gradle-publish-secret }}
        GPG_PRIVATE_KEY: ${{ inputs.gpg-private-key }}
        GPG_PASSWORD: ${{ inputs.gpg-password }}
      run: ./gradlew publishPlugins -Prelease=true
