name: PR Check

on:
  - pull_request
  - workflow_dispatch

jobs:
  checks:
    uses: LikeTheSalad/github-tools/.github/workflows/pr-check.yml@main
    with:
      checks-command: ./checks.sh
      run-instrumentation-tests: true
      instrumentation-test-command: ./gradlew -p demo-app connectedDebugAndroidTest
    secrets: inherit
