name: Prepare release

on: workflow_dispatch

jobs:
  prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Verify prerequisites
        run: |
          if [[ $GITHUB_REF_NAME != main ]]; then
            echo This workflow should only be run against main
            exit 1
          fi
      - uses: ./.github/actions/setup-bot-git-user
        id: bot
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v6
      - name: Setting variables
        id: variables
        run: |
          version=$(cat gradle.properties | grep -Po "(?<=version=)\d+\.\d+\.\d+")
          echo "The version is $version"
          {
            echo "version=$version"
            echo "release_branch=release/$version"
          } >> "$GITHUB_OUTPUT"
      - name: Creating release branch
        env:
          RELEASE_BRANCH: ${{ steps.variables.outputs.release_branch }}
        run: |
          git checkout -b $RELEASE_BRANCH
          git push --set-upstream origin $RELEASE_BRANCH
      - name: Updating the CHANGELOG.md file
        env:
          VERSION: ${{ steps.variables.outputs.version }}
        run: sh .github/scripts/update-changelog.sh
      - name: Updating README.md version references
        env:
          VERSION: ${{ steps.variables.outputs.version }}
        run: |
          sed -i 's/id("com.likethesalad.aaper") version "[0-9]\+\.[0-9]\+\.[0-9]\+"/id("com.likethesalad.aaper") version "'"$VERSION"'"/g' README.md
      - name: Creating release branch PR
        env:
          GH_TOKEN: ${{ steps.bot.outputs.token }}
          VERSION: ${{ steps.variables.outputs.version }}
          RELEASE_BRANCH: ${{ steps.variables.outputs.release_branch }}
        run: |
          message="Prepare release $VERSION"
          branch="pre-release/$VERSION"

          git checkout -b $branch
          git commit -a -m "$message"
          git push --set-upstream origin $branch
          gh pr create --title "[$RELEASE_BRANCH] $message" \
                       --body "$message." \
                       --base $RELEASE_BRANCH
