name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Verify prerequisites
        run: |
          if [[ $GITHUB_REF_NAME != release/* ]]; then
            echo This workflow should only be run against release branches
            exit 1
          fi
      - uses: ./.github/actions/setup-bot-git-user
        id: bot
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/publish-maven-central
        with:
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-password: ${{ secrets.GPG_PASSWORD }}
      - uses: ./.github/actions/publish-gradle-portal
        with:
          gradle-publish-key: ${{ secrets.GRADLE_PUBLISH_KEY }}
          gradle-publish-secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-password: ${{ secrets.GPG_PASSWORD }}

  post_release:
    name: Post release
    runs-on: ubuntu-latest
    needs:
      - release
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: ./.github/actions/setup-bot-git-user
        id: bot
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-java
      - name: Creating a GH release
        id: variables
        env:
          GH_TOKEN: ${{ steps.bot.outputs.token }}
        run: |
          version=$(cat gradle.properties | grep -Po "(?<=version=)\d+\.\d+\.\d+")
          tag="v$version"
          git tag $tag
          git push origin tag $tag

          gh release create --target $GITHUB_REF_NAME \
                            --title "$version" \
                            $tag
      - name: Bump version
        run: |
          ./gradlew versionBump
          git commit -a -m "Bumping version"
          git push
      - name: Create PR to main
        env:
          GH_TOKEN: ${{ steps.bot.outputs.token }}
        run: |
          message="Prepare for the next release"
          gh pr create --title "$message" \
                       --body "$message." \
                       --base main
