name: Sync github-tools wrappers
on:
  workflow_dispatch:
jobs:
  sync:
    uses: LikeTheSalad/github-tools/.github/workflows/sync-wrappers.yml@main
    with:
      app-id: '${{ vars.APP_ID }}'
    secrets: inherit
